spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring-Security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: QAQm..02r
    driver-class-name: com.mysql.cj.jdbc.Driver
